# Use Defaults 
use_default_settings: true

# Override Defaults
general:
  # Browser tab title
  instance_name: "SearXNG"
  # Disable this stuff
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  # 0: None, 1: Moderate, 2: Strict
  safe_search: 0
  # Formats allowed
  formats:
    - html
    # - csv
    # - json
    # - rss

  # Auto complete - blank to disable
  # "dbpedia", "duckduckgo", "google", "yandex", "seznam" 
  # "startpage", "swisscows", "qwant", "wikipedia"
  autocomplete: "startpage"
  # Number of characters to trigger auto complete
  autocomplete_min: 4

  # Search language - blank to detect from browser
  # Or codes from here: 
  # https://github.com/searxng/searxng/blob/master/searx/languages.py
  default_lang: "en-US"

# Result Categories
# Commenting out does NOT remove tabs as docs say
# Un-documented, but appears each tab is a dictionary
# Still looking for solution
categories_as_tabs:
  files:
  general:
  images:
  # it:
  map:
  # music: 
  news:
  science:
  # social media: 
  videos:

# User Interface
ui:
  # Cache busting of static files
  static_use_hash: true
  # Infinite scroll (true) or paginated (false) search results
  infinite_scroll: true  
  # Theme name
  default_theme: simple
  # Center (true) or left-align (false) search results
  center_alignment: true  
  theme_args:
    # auto, light, dark
    simple_style: light
  # Source for cached pages - uncomment 1
  cache_url: https://web.archive.org/web/
  # cache_url: https://webcache.googleusercontent.com/search?q=cache:
  # cache_url: https://archive.today/

# Server
server:
  # "POST" is more secure and works in Chrome / Chromium-based browsers
  # "GET" fixes Firefox back button issue
  method: "POST"
  # Proxy image results with SearX (true)
  image_proxy: true

