version: '2'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    ports:
      # - 8000:8000   # 💡 Edge agents
      - 9443:9443     # ⚠️ Web UI
    volumes:
      - /volume1/docker/portainer-ce:/data
      - /var/run/docker.sock:/var/run/docker.sock
