version: '2'

networks:
  default:
    name: nas_network

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    ports:
      - 7680:8000   # Edge agents
      - 7643:9443   # Web UI
    volumes:
      - /volume1/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 172.77.0.6
