version: "2"

networks:
  default:
    name: nas_network 

services:
  pi-hole:
    image: pihole/pihole:latest
    container_name: pi-hole
    hostname: pi-hole
    restart: unless-stopped
    ports:
      - "7453:53/tcp"   # DNS traffic
      - "7453:53/udp"   # DNS traffic
      - "7480:80/tcp"   # Web UI
    environment:
      - WEBPASSWORD=${WEBPASSWORD}  # .env
      - TZ=${TZ}  # .env
      - DNSMASQ_LISTENING=local
    volumes:
      - /volume1/docker/pi-hole/etc-pihole:/etc/pihole:rw
      - /volume1/docker/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      default:
        ipv4_address: 172.29.7.4

  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    hostname: "unbound"
    restart: unless-stopped
    ports:
      - "7553:53/tcp"   # DNS traffic
      - "7553:53/udp"   # DNS traffic
    networks:
      default:
        ipv4_address: 172.29.7.5
