version: "2"

networks:
  default:
    name: nas_network

services:
  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    hostname: "unbound"
    restart: unless-stopped
    volumes:
      - /volume1/docker/pi-hole/unbound:/opt/unbound/etc/unbound
    ports:
      - "7553:53/tcp"   # DNS traffic
      - "7553:53/udp"   # DNS traffic
    networks:
      default:
        ipv4_address: 172.29.7.5

  pi-hole:
    depends_on: [unbound]
    image: pihole/pihole:latest
    container_name: pi-hole
    hostname: pi-hole
    restart: unless-stopped
    ports:
      - "7453:53/tcp"   # DNS traffic
      - "7453:53/udp"   # DNS traffic
      - "7480:80/tcp"   # Web UI
      - "7443:443/tcp"  # Web UI
    dns:
      - 127.0.0.1
      - 172.29.7.5  # Unbound IP
    environment:
      TZ: "America/New_York"      # ⚠️ Server time zone
      WEBPASSWORD: "TempPassWord" # A temp PW
      ServerIP: 172.29.7.4     # Pi-hole IP
      DNS1: 172.29.7.5         # Unbound IP
      DNS2: 172.29.7.5         # Twice else defaults to Google
    volumes:
      - /volume1/docker/pi-hole/etc-pihole:/etc/pihole
      - /volume1/docker/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      default:
        ipv4_address: 172.29.7.4
