version: "2"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.77.0.0/24
        - gateway: 172.77.0.1

services:
  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    hostname: "unbound"
    restart: unless-stopped
    volumes:
      - /volume1/docker/pi-hole/unbound:/opt/unbound/etc/unbound
    ports:
      - "8753:53/tcp"   # DNS traffic
      - "8753:53/udp"   # DNS traffic
    networks:
      default:
        ipv4_address: 172.77.0.3

  pi-hole:
    depends_on: [unbound]
    image: pihole/pihole:latest
    container_name: pi-hole
    hostname: pi-hole
    restart: unless-stopped
    ports:
      - "8753:53/tcp"   # DNS traffic
      - "8753:53/udp"   # DNS traffic
      - "8780:80/tcp"   # Web UI
      - "8743:443/tcp"  # Web UI
    dns:
      - 127.0.0.1
      - 172.77.0.3  # Unbound IP
    environment:
      TZ: "America/New_York"   # ⚠️ Server time zone
      WEBPASSWORD: 'changeme'  # ⚠️ A temporary PW
      ServerIP: 172.77.2       # Pi-hole IP
      DNS1: 172.77.0.3         # Unbound IP
      DNS2: 172.77.0.3         # Twice else defaults to Google
    volumes:
      - /volume1/docker/pi-hole/etc-pihole:/etc/pihole
      - /volume1/docker/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      default:
        ipv4_address: 172.77.0.2


